### ISSUE TITLE
Issue when running on Magma

### ISSUE THREAD

**Issue by superpurplegamer** [ichttt/FirstAid#101]
When I run rlcraft (using this mod) on magma it makes you indestructible meaning you can't die.

**Comment by Kyrixus** [comment]
I have also run into this issue when running a magma server. no solution to offer just adding validity. If you run a mohist server it will work but wont show your hearts. the server reads the mod as a client side only mod and puts it in a delete folder.

**Comment by ichttt** [comment]
FirstAid is only has official support for "normal" Forge and SpongeForge. If you want another server software, it's an issue with them, as my mod works perfectly fine with normal Forge and SpongeForge
