### ISSUE TITLE
Config File Name Space Issue

### ISSUE THREAD

**Issue by Charles445** [ichttt/FirstAid#104]
Ran into a rare case where a server owner's setup couldn't handle the space in the filename "First Aid.cfg". It was causing the config file to not be read properly.
I'm not sure why their setup couldn't handle a file with a space in it.

Edit: This was observed with firstaid-1.6.14 for 1.12.2

**Comment by ichttt** [comment]
Fixed in 1.6.15 beta for mc 1.12.2. If no bigger issues arise, this will be promoted to a release soon, and a version for 1.16 will follow.
