### ISSUE TITLE
For Consideration: I made new textures for FirstAid's items and mob_effect, as well as a few rotated bandage/plaster recipes for convenience

### ISSUE THREAD

**Issue by StygianEmperor** [ichttt/FirstAid#110]
I don't know GitHub very well, so apologies in advance if this isn't the right place for this.

I used your existing textures for the items as a base and altered them to be slightly more in-line with Minecraft's art style - as well as making a few rotated bandage/plaster recipes for convenience - for my private server. I was pretty happy with how they turned out, so, _perhaps presumptuously,_ I considered you might like them enough to fix them up for the actual mod. 

I don't know if that would be anything you're interested in, but I'll upload them here for review if you get some time.

**Textures:**
![bandage](https://user-images.githubusercontent.com/75293860/103597703-7c401e00-4ec6-11eb-83dc-6681dbacba99.png)
![morphine](https://user-images.githubusercontent.com/75293860/103597705-7c401e00-4ec6-11eb-917a-e681bd4ef479.png)
![plaster](https://user-images.githubusercontent.com/75293860/103597706-7cd8b480-4ec6-11eb-9194-99926b7dfeaa.png)
![morphine_mob_effect](https://user-images.githubusercontent.com/75293860/103597732-8b26d080-4ec6-11eb-8df3-e80f78e59ec8.png)

**Recipes** (change back to .json of course)**:**
[bandage.txt](https://github.com/ichttt/FirstAid/files/5767709/bandage.txt)
[bandage_b.txt](https://github.com/ichttt/FirstAid/files/5767710/bandage_b.txt)
[plaster.txt](https://github.com/ichttt/FirstAid/files/5767711/plaster.txt)
[plaster_b.txt](https://github.com/ichttt/FirstAid/files/5767712/plaster_b.txt)
[plaster_c.txt](https://github.com/ichttt/FirstAid/files/5767713/plaster_c.txt)
[plaster_d.txt](https://github.com/ichttt/FirstAid/files/5767714/plaster_d.txt)

I also changed `"item": "minecraft:string"` to `"tag": "forge:string"` in the recipes so they could utilize any modded version of string - don't know if the default limitation was intentional or not. `"tag": "forge:wool"` might also be commonly used but I haven't looked into it.

**Comment by ichttt** [comment]
The recipe changes look interesting, thanks for that! I hope I have time to do a more detailed look at it soon-ish.

I don't think I will include your textures though, cause I still like my own, but maybe that's just me being not objective.

**Comment by ichttt** [comment]
I ended up changing textures, but I used different ones.
See 99d2ec257afa1026997fa9aafdb261384903e41d
