### ISSUE TITLE
Spawn with no health

### ISSUE THREAD

**Issue by TsplayerT** [ichttt/FirstAid#111]
I have the same problem as case #86 and I believe it is because of the `Spice of Life: Carrot Edition` mod
I tested without this mod and there was no problem.

Minecraft: 1.16.4
Forge: 35.1.13
firstaid: 1.9.5
solcarrot: 1.16.3-1.9.8

[latest.log](https://github.com/ichttt/FirstAid/files/5756427/latest.log)
[debug.log](https://github.com/ichttt/FirstAid/files/5756428/debug.log)

**Comment by ichttt** [comment]
Should be fixed, see #115
