### ISSUE TITLE
Always display overlay?

### ISSUE THREAD

**Issue by MastaNub** [ichttt/FirstAid#112]
I'm pretty sure I managed to do that like a year ago or so.
When disabling vanilla health and using the overlay to display each body part separately it only appears when taking damage/regenerating. Is there a way to always display the overlay? Because I took this screenshot and I don't know which version it is https://prntscr.com/wj013l I'm currently running 1.6.14 (RLCraft).

**Comment by TsplayerT** [comment]
Try to make the `X-axis offset` value smaller, for example `10`

**Comment by ichttt** [comment]
yes, there should be something like visibleDurationTicks in the overlay config. Set that to -1
