### ISSUE TITLE
Hunger bar texture becomes glitched when in the presence of a boss mob.

### ISSUE THREAD

**Issue by roccscout** [ichttt/FirstAid#114]
Title says it all. I've had this glitch for at least 10 months, now.

When you are **within range** of a Boss Mob (vanilla or modded) to show their boss health bar, your hunger bar texture gets messed up and becomes unrecognizable. The second you step away from a boss enough to leave the boss bar, your hunger bar texture is immediately returned to normal.

I hope this is a quick fix!
![Inked2021-01-16_16 05 58_LI](https://user-images.githubusercontent.com/71896090/104825138-43cd0800-5815-11eb-98a1-c1160f8a11ab.jpg)

![Inked2021-01-16_16 06 28_LI](https://user-images.githubusercontent.com/71896090/104825139-44fe3500-5815-11eb-8d14-2dfa078fd591.jpg)

**Comment by ichttt** [comment]
Will be fixed in the 1.9.6 non-beta version going up in a few days.

**Comment by roccscout** [comment]
What about a fix for 1.12.2?

**Comment by ichttt** [comment]
will also be in the next 1.12.2 version

**Comment by roccscout** [comment]
Still no 1.12.2 fix?
