### ISSUE TITLE
How to change the UI from the normal Body outline to the Hearts? (and how to change the position)

### ISSUE THREAD

**Issue by KirkLHTC** [ichttt/FirstAid#117]
I'm just making this jsut for some help, as I forget entirely how to switch the UI to the hearts and to change what corner of the screen the UI is in. I'm using 1.16.4 and I can't play Survival without the UI covering the Xaero's Minimap. Just some explanation would be fine.

**Comment by ichttt** [comment]
Unfortunally, forge doesn't have a generic in game GUI for config changes yet. You can change by manually editing the config file.
It is under your minecraft installation directory (%appdata%/.minecraft/config on Windows). In there, you should fine a firstaid-client.toml. Open that with a text editor like the windows notepad or notepad++.  You can tweak the values there. You can also live edit the config while the game is running, and it should pick up the changes when you save
