### ISSUE TITLE
(1.12.2) Random Frozen Skeletons?

### ISSUE THREAD

**Issue by KiloTracer** [ichttt/FirstAid#119]
![image](https://user-images.githubusercontent.com/79031970/108796198-cd2ad500-754d-11eb-8864-9bd076bfb9a3.png) 

These skeletons spawn in the day and mostly under trees (I know that's what they're supposed to do just wanted to point it out) The skeletons spawn in frozen and you can hit them but only once until they're invincible and frozen 

![image](https://user-images.githubusercontent.com/79031970/108797195-3f9cb480-7550-11eb-9b7a-cdb768f65866.png)

![image](https://user-images.githubusercontent.com/79031970/108797214-49261c80-7550-11eb-8fb3-d874fc21d967.png)

![image](https://user-images.githubusercontent.com/79031970/108797230-53e0b180-7550-11eb-93c1-77d94e38de1a.png)

![image](https://user-images.githubusercontent.com/79031970/108797241-5c38ec80-7550-11eb-9be1-df50a66f7bf4.png)

![image](https://user-images.githubusercontent.com/79031970/108797254-665aeb00-7550-11eb-893b-6978ffdad83a.png)

![image](https://user-images.githubusercontent.com/79031970/108797268-6e1a8f80-7550-11eb-8730-574d5658b8c4.png)

![image](https://user-images.githubusercontent.com/79031970/108797274-7246ad00-7550-11eb-9f4f-3921bfff490c.png)

Sorry I did not feel like typing my whole modlist out I can if u want

**Comment by ichttt** [comment]
Doesn't sound like a first aid issue, I don't modify any mobs other than players.
