### ISSUE TITLE
Too little space for body parts text

### ISSUE THREAD

**Issue by raspopov** [ichttt/FirstAid#12]
It will be nice to have a more room for larger button labels in the Health dialog (and HUD) for other languages, or use a bit smaller font size.

**Comment by ichttt** [comment]
I plan on adding a value the lang file can modify which contains the space between the edge of the screen and the health

**Comment by raspopov** [comment]
Will it be too difficult to make a dynamic sized buttons and HUD? I.e. button automatically adjusted to fit its text.

**Comment by ichttt** [comment]
It is possible fot the overlay, but for the big menu it isn't that easy, because it is hardcoded. The only possible way there is to make it bigger by default.

**Comment by ichttt** [comment]
I could not make the texture much I already was close to the maximum, but I now set the GUI to the max value and made the HUD choose it's size dynamically
