### ISSUE TITLE
[Feature Request] Add an option to disable dying on loss of head and/or body hearts.

### ISSUE THREAD

**Issue by ddmjr22** [ichttt/FirstAid#125]
Just that. An option to keep the actual limb dubuff part of the mod without ko's to the head/body.

Edit: After rereading this I realized what I wrote can possibly be misunderstood. 
What I'm requesting is an option to disable instant death when losing all of the remaining health points to the head or body. Essentially, this means they will have the same function as an ordinary limb. When head/body get damaged you will still get the debuff ( blindness, nausea etc), but will only die when you lose All remaining hearts for every other limb. 

Or, maybe allow a configurable chance percentage on whether you will die or not from losing all head or body hitpoints.

**Comment by roccscout** [comment]
I believe this is already a thing.

**Comment by ddmjr22** [comment]
> I believe this is already a thing.

In 1.16.5? If so, please do tell how. Last time I check I didn't see anything in the config.

**Comment by ichttt** [comment]
yes, this config option already exists. It's called `causeDeathBody` and `causeDeathHead`. It's hidden in the server config. You can find it by going to your minecraft folder (usually %appadata%/.minecraft), then saves, then your save that you use the mod on and than serverconfig. In that folder, you should find a firstaid-server.toml that you can edit. Set both values to false. Repeat this for all the saves that you currently play with the mod. If you want this to apply for new worlds/saves in the futre as well, copy the firstaid-server.toml to the defaultconfigs folder (located in your minecraft folder).
