### ISSUE TITLE
Apotheosis

### ISSUE THREAD

**Issue by Petrisis** [ichttt/FirstAid#133]
its more a question than an issue:
How does FirstAid handle Apotheosis Affixes? Theyre adding flat amounts of e.g. Armor and Armor Toughness which doesnt get converted into local armor/toughness. Do these global attributes work? or are they just invalid and get ignored (in this case i'd wish for an integration of apotheosis into FirstAid's System).

![grafik](https://user-images.githubusercontent.com/31795322/127737802-a858d948-f692-4c42-a34a-71235141c3d3.png)

**Comment by ichttt** [comment]
Closing as answered
