### ISSUE TITLE
Redesign proposal with image

### ISSUE THREAD

**Issue by Rozarke** [ichttt/FirstAid#134]
Hi, I love your mod but your design is too flat and inconsistent with minecraft. So I made you a redesign of your mod,  hope you like it.

image: https://imgur.com/a/kgLkj27

If you are interested in my proposal, please let me know in response.

**Comment by ichttt** [comment]
Hi,
thanks for the suggestion!
I really like the style of some of the new icons. If you are willing to provide them to me, I want to include them into the 1.17 release, as vanilla changed a lot of item textures there as well. Just open a Pull Request to the 1.16.x branch for now or upload the images elsewhere and send me a link.
Many thanks!

**Comment by ichttt** [comment]
Implemented in 99d2ec257afa1026997fa9aafdb261384903e41d
