### ISSUE TITLE
[Bug] New hitbox clips through thin walls

### ISSUE THREAD

**Issue by zndrmn** [ichttt/FirstAid#135]
Minecraft Version 1.16.5
OptiFine Version G8
Forge Version 36.2.0
Mod Version firstaid-1.9.6

The new hitbox for the 4 areas of the body and slightly bigger than the vanilla one, so this could be the reason to mobs being able to hit the player through thin walls / the corner of walls.

**Comment by ichttt** [comment]
That's actually not a problem. The new hitboxes are a bit bigger, but the hit registration is still unchanged. Minecraft uses the normal hit box for detecting if a hit has occured or not. The new hitboxes are only used to attribute this damage to a specific region in a second step. So there is no possibility how that can change vanilla behaviour
