### ISSUE TITLE
First Aid Health Position Keeps Jumping Around For All Players

### ISSUE THREAD

**Issue by SilverHatTrick** [ichttt/FirstAid#150]
https://gyazo.com/37a7854778b6dec8ca5f0bc8dc35db1c

Not really sure what is happening, but it's rather disorientating for the players. Occurs every 5 seconds or so.

**Comment by Jollyolsport** [comment]
Im getting the same issue too now; did you just recently update your mods?

**Comment by rperraudeau** [comment]
I was experiencing this too.
I find out that was because of the easteregg config is enabled.
Seems like it was a trick for Halloween or something.

If you want to disable it just the the enableEasterEggs = false in the misc section in firstaid-client file

**Comment by ichttt** [comment]
Yeah it's an easter egg. I made it much less frequent in newer versions though
