### ISSUE TITLE
Can't load minecraft with optifine and first aid

### ISSUE THREAD

**Issue by amandexspeed** [ichttt/FirstAid#153]
When I try to use optifine and this mod minecraft crashes .
The strange thing is that I managed to use it once without entering a world and configured some things with the mod configured by mrcrayfish. After that it just crashed. I uninstalled the mod and installed it several times and even took the configured.
[crash-2021-11-11_09.01.39-fml.txt](https://github.com/ichttt/FirstAid/files/7520272/crash-2021-11-11_09.01.39-fml.txt)
[latest.log](https://github.com/ichttt/FirstAid/files/7520273/latest.log)

**Comment by ichttt** [comment]
Can you send me your first aid config file please?

**Comment by ichttt** [comment]
Closing as stale and unanswered
