### ISSUE TITLE
[1.17.1] Nothing appears in the Igloo and Minecarts with Chests.

### ISSUE THREAD

**Issue by Mihail001** [ichttt/FirstAid#156]
When I use First Aid 1.10.1 for 1.17.1 together with the 1.17.1-Forge-37.1.0 , then nothing spawn (no items inside) in the minecarts with the chest inside (which are in mineshafts). The same problem is in ordinary chests in the igloo.
Mineshaft:
![2021-12-06_20 12 18](https://user-images.githubusercontent.com/74407310/144892986-bb8ffc0c-7576-4de6-bfc3-11c18ae5638b.png)
![2021-12-06_20 12 29](https://user-images.githubusercontent.com/74407310/144893016-6d1eda48-289a-4cfe-8f5e-81273e6190c1.png)
Igloo:
![2021-12-06_20 21 18](https://user-images.githubusercontent.com/74407310/144893025-4100b4af-de06-494b-9a9d-7d63ea233120.png)
![2021-12-06_20 21 28](https://user-images.githubusercontent.com/74407310/144893031-7be453bd-c6c1-4858-ac2e-a061e056e3ec.png)

**Comment by ichttt** [comment]
Should be fixed in 1.18.x and upwards, I semi-rewrote loot handling in 4719199344daa090180764d8349e88a7eb8646b4

**Comment by Mihail001** [comment]
Thanks!
