### ISSUE TITLE
(1.16.5) Limb health cap at 6 hearts with ScaleMaxHealth enabled in config but doesn't go farther than 6 hearts

### ISSUE THREAD

**Issue by GhostLupine** [ichttt/FirstAid#159]
So I've been trying to figure out why the limb health caps at 6 hearts. I've looked everywhere in the config and see scale max health is enabled, but it doesn't scale from max health. I don't know why it doesn't work, but I've tried everything to fix it, and it just changes nothing.

**Comment by ichttt** [comment]
Set capMaxHealth to false and it should work
