### ISSUE TITLE
bug with PlayerRevive

### ISSUE THREAD

**Issue by VirtualGaming1** [ichttt/FirstAid#18]
there is a bug with the lastest mod version and that its not doing as its was doing once you get revived by a player and keep make the player unable to hit any mob or player after revive and after use of bandage the part health dose not regain.

**Comment by VirtualGaming1** [comment]
look like that you are missing isRevived() in your coding. because before i notice that before i updated that when you get revived your major health that is 0 is set to 1 to prevent the game thinking of you dead or trying to kill you.

**Comment by ichttt** [comment]
oh no, did I break it again... Will fix when I find the time to do so
