### ISSUE TITLE
Respawn issue with PlayerRevive

### ISSUE THREAD

**Issue by tuxedoderpycat** [ichttt/FirstAid#180]
When being revived or letting the timer hit 0, everything functions normally, but when you hold left click to give up, it instead just drops you right where you died. This issue occurs with the latest version of both mods on 1.18.2. Removing First Aid fixes the bug with player revive.

**Comment by CreativeMD** [comment]
They code responsible for this can be found [here](https://github.com/CreativeMD/PlayerRevive/blob/90eb51d3c3d4680123cd5ed743d53c99dfd56e3c/src/main/java/team/creative/playerrevive/server/PlayerReviveServer.java#L74).

**Comment by Sember225** [comment]
I also have this issue

**Comment by Sember225** [comment]
Still in 1.18.2 here, I have some additional information. 
In a server environment, using First Aid and Player Revive. 
When a player dies they are downed as they should be. If the player waits a minute and expires naturally, they'll respawn at their spawn no issue. 

The only time this issue occurs is when the player "gives up", they will spawn back at the exact point of giving up. This leads me to believe it's a player revive issue, not I'm not too versed in these things.

**Comment by jhoelzzz19** [comment]
Hay alguna solución para el error #180?
O si es mejor cambiar algo

**Comment by ichttt** [comment]
Should be fixed in [FirstAid 1.11.2](https://legacy.curseforge.com/minecraft/mc-mods/first-aid/files/5532498)
