### ISSUE TITLE
Datapack for this mod

### ISSUE THREAD

**Issue by LucasInacio11** [ichttt/FirstAid#186]
Since this mod covers a serverconfig file for some configurations, like body and head hardcore hearts, is there a way to add a datapack or something to configure the world settings?
I dont use body and head hardcore mode, but these options are only avaliable after creating the world.
It's boring to create a world>exit>change config>enter again for every time I need.

**Comment by ichttt** [comment]
Some settings like debuffs and damage distributions have been moved to datapacks. I won't move the rest, though, as this is quite complicated and I just use the standard forge config system
