### ISSUE TITLE
Crafting Recipe

### ISSUE THREAD

**Issue by latisss** [ichttt/FirstAid#188]
Crafting of bandages are different.
![image](https://user-images.githubusercontent.com/121942290/210543151-498dd554-ed32-4520-a6e1-8997db7833d0.png)
Can u please help with that? this should be alot easier, it makes game incredibly HARDER.

**Comment by latisss** [comment]
its 2.9.1c , 1.12.2 from curseforge

**Comment by latisss** [comment]
2.9.1c from curseforge - singleplayer

**Comment by latisss** [comment]
2.9.1c rlcraft from curseforge - singleplayer
first aid 1.6.20

**Comment by DeshiDesu** [comment]
These are custom recipes created with the CraftTweaker mod using zenscript. If you don't like them then delete the lines removing the first aid recipes and custom ones from the scripts.

**Comment by ichttt** [comment]
Yeah, you can tweak the recipes yourself in newer versions using datapacks and in older versions using something like CraftTweaker
