### ISSUE TITLE
[1.18.2] Crash if player dies when sleeping

### ISSUE THREAD

**Issue by DeshiDesu** [ichttt/FirstAid#195]
Version of First Aid used:

> firstaid-1.11.1.jar

When used with somnia awoken mod, you can simulate the world instead of skipping the night.

Using the Cold Sweat mod (A temperature mod for context), allows the player to take damage after reaching high or low temperatures. Instead of exiting the bed after taking temperature damage, the player stays on the bed until the player dies, which leads to a crash.

To reproduce this:

> 1. Sleep at night
> 2. Accumulate -100 temperature
> 3. Wait for crash

Other mods related to the crash:

> Somnia-Awoken-1.18.2-3.0.105.jar
> ColdSweat-2.2-b03e.jar

The result of the crash:

> java.lang.IllegalArgumentException: Player DeshiDesu is missing a damage model!
>     at ichttt.mods.firstaid.common.util.CommonUtils.lambda$getDamageModel$1

Here is my crash log for reference:
[crash-2023-04-05_20.33.12-server.txt](https://github.com/ichttt/FirstAid/files/11170191/crash-2023-04-05_20.33.12-server.txt)

**Comment by ichttt** [comment]
Fixed in FirstAid 1.11.2

**Comment by DeshiDesu** [comment]
thanks
