### ISSUE TITLE
[Crash] Player is missing a damage model!

### ISSUE THREAD

**Issue by Sember225** [ichttt/FirstAid#198]
[Crash log](https://pastebin.com/e0fUr9RK)

Minecraft Ver: 1.18.2
Forge Ver: 40.2.0
Mod Ver: 1.11.1

Player describes taking damage from a drowned before crashing. I couldn't replicate it when testing on my end. 
Any insights would be great!

**Comment by ichttt** [comment]
Fixed in FirstAid 1.11.2
