### ISSUE TITLE
gamerule naturalRegeneration problem on removing mod

### ISSUE THREAD

**Issue by Thyriel** [ichttt/FirstAid#2]
A thing i noticed after removing firstaid for now:
It seems with the option to disable food life regeneration you used the vanilla command "gamerule naturalRegeneration false" so after removing the mod this gamerule stays active.
I wouldn't know a real fix for that, but you should write it on the mods site that on mod removal players need to execute "gamerule naturalRegeneration true" to reenable regeneration again.

**Comment by ichttt** [comment]
I can fix this for future versions, but it will only work with users who didn't load the world with an older version of the mod.

**Comment by ichttt** [comment]
Sorry, but the fix I tried did not work. I have to revert it, but I updated the download site to reflect the information. Thanks for the report anyways!

**Comment by Thyriel** [comment]
I didn't thought that this would be fixable at all as you can't run any code after a mod had been deleted. Imho the Note you put on curseforge should be good enough ;)

**Comment by ichttt** [comment]
I was thinking of reverting the value on world save, this way, it wouldn't be in your save. But that didn't work as expected
