### ISSUE TITLE
List of Mods that need a Capability fix.

### ISSUE THREAD

**Issue by VirtualGaming1** [ichttt/FirstAid#20]
Hay I want to make this so there are list of mods that need a Capability fix. If this is close that mean there is no mods that need Cap Fix.

Zombie Awareness by Corosauce: Blood spot spawn no mater what the health of any part or average health is. https://github.com/Corosauce/ZombieAwareness/issues/29

**Comment by ichttt** [comment]
I don't know what you mean and I don't have any idea how this mod works... I'll take a look when I find the time to do so.

**Comment by VirtualGaming1** [comment]
I thinks this is mainly on the side of ZombieAwarness mod but you can try tho.

**Comment by ichttt** [comment]
@VirtualGaming1 could you try the ZombieAwareness thing again? I fixed a little thing in 1.4.7 that could resolve this, but I'm not sure

**Comment by VirtualGaming1** [comment]
I can try it going be harder to do since I don't have a server anymore and my computer is doing some what ok.

**Comment by ichttt** [comment]
I should be fixed, and as no one is complaining, I'm closing this. Reopen if you validate that the issue still persists
