### ISSUE TITLE
[1.19.4] java.land.NoSuchFieldError: f_19315_

### ISSUE THREAD

**Issue by AtomicBlastPony** [ichttt/FirstAid#201]
[crash-2023-05-02_05.27.20-fml.txt](https://github.com/ichttt/FirstAid/files/11369261/crash-2023-05-02_05.27.20-fml.txt)
Error when trying to start the game.

**Comment by ichttt** [comment]
The 1.19.3 version does not work with 1.19.4. I am currently working on a new version

**Comment by ichttt** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/first-aid/files/4517272
