### ISSUE TITLE
Player  is missing a damage model

### ISSUE THREAD

**Issue by sir-Robson** [ichttt/FirstAid#204]
Hello and welcome.
please kindly help me
when exiting the world there is a crash with this main message

''Player "name"  is missing a damage model''

What could be causing this and how to deal with this problem?

minecraft 1.18.2
forge 40.2.2
FirstAid - 1.11.1

I've included the full Cash Log below

crash-2023-05-19_00.10.12-server.txt](https://github.com/ichttt/FirstAid/files/11511922/crash-2023-05-19_00.10.12-server.txt)

Robson.

**Comment by bradenq95** [comment]
getting the same issue here but forge 40.2.1 on a multiplayer server only. Logs look similar to OP, and this issue only happens randomly upon death. Prevents the user from rejoining.

**Comment by sir-Robson** [comment]
thanks for the answer i will try it.
I found not compatible with mods 
- Spice of Life: Carrot Edition
- Spice of Life: Potato Edition

after removing it from the modpack the problem went away>
I don't know what caused this error but after removing them the game doesn't crash after leaving the world

**Comment by TqLxQuanZ** [comment]
Having this issue as well, it's quite random and for multiplayer the client will get kick out but still able to rejoin back.

**Comment by sir-Robson** [comment]
> Having this issue as well, it's quite random and for multiplayer the client will get kick out but still able to rejoin back.

That's right, nothing happens except that the whole game closes

**Comment by bradenq95** [comment]
on our end the player that crashes CAN'T rejoin until we remove first-aid, reload the server to get them back on and respawned, then put first-aid back on lol

**Comment by ichttt** [comment]
Fixed in FirstAid 1.11.2
