### ISSUE TITLE
cannot disable

### ISSUE THREAD

**Issue by Sirenzero** [ichttt/FirstAid#212]
how does one disable this mod. when included in modpacks, like RLcraft, it is automatically enabled, so how does one disable this? i have tried to disable from the mods page in game and the option doesn't work, i have tried removing the file from the mod pack entirely and that causes it to crash when attempting to boot up the game. if anybody has a solution (besides getting good (don't ask)) please say.

**Comment by Sirenzero** [comment]
this may be an issue with the modpack and not the mod itself, but if anybody has any ideas that would be great.

**Comment by ichttt** [comment]
Yeah RLCraft deeply integrates FirstAid, so other mods depend on it. I am affraid you can't just remove it from that pack without affecting other mods
