### ISSUE TITLE
Client think im dead but im not on server when my hunger bar goes down.

### ISSUE THREAD

**Issue by VirtualGaming1** [ichttt/FirstAid#22]
Hay im having an issue on my modpack when i switch over to the latest version that when ever my hunger start going down that then my client think that i am dead but the server still saying im alive. dont know if this is new bug or a Capability bug with TAN (Though as Nails) and will be doing further testing.

**Comment by VirtualGaming1** [comment]
just looked on twitch app and found out there is an update will be testing with that

**Comment by VirtualGaming1** [comment]
just confirm that it is a bug of First aid mod with this version and the version from before. im guessing that you might need to look at the hunger coding or something that you change in it because everytime that hunger goes down the client side think you just got killed.

**Comment by ichttt** [comment]
Please clarify: Do you mean something desync when your food bar goes to zero, and why do you think the client is thinking you are dead?

**Comment by VirtualGaming1** [comment]
i dont know if it is desync but if you have 20/20 food and then gose to 19/20 then client side thinks you are dead with average health 0 (do not know if that is with the body health still or not) and will not be able to respawn unless leave the server and rejoin. so far what i am thinking is this is client side coding that something got changed that is should not. i am thinking that client side is dead because the server is still sending the client pos and then the screen is shacky like.

**Comment by ichttt** [comment]
I am finally able to reproduce this. It seems like the bug does only exist when scaleMaxHealth is enabled. Looking into it.
