### ISSUE TITLE
Request: Compatible with The-Hordes

### ISSUE THREAD

**Issue by wumengzhixing** [ichttt/FirstAid#222]
Version：1.18.2
First Aid：1.11.1
The-Hordes：1.18.2-1.2.1a.jar
Forge：40.2.10

I found that when the player was infected and died, missing a damage model caused the game to crash. Can you try to make it compatible?
[crash-2024-01-04_15.38.36-server.txt](https://github.com/ichttt/FirstAid/files/13840952/crash-2024-01-04_15.38.36-server.txt)

**Comment by ichttt** [comment]
Fixed in FirstAid 1.11.2
