### ISSUE TITLE
NaN Health Bug

### ISSUE THREAD

**Issue by SuoHouDaiShi** [ichttt/FirstAid#224]
# I Not have good English,so I will use Translate Softwares
Use the command to obtain some equipment that can increase health, wear it, and wait for the full recovery of health. After the recovery of health is complete, remove all the equipment that increases health, and you will find that your health has been deducted. After a few rounds, open a container and retrieve items at will. At this time, **directly exit the game (such as ALT+F4 or use the task manager to terminate the process)**, and enter the game again, At the moment of entering the archive, it will prompt "You're dead!" and then click on "Rebirth". At this time, press H to open the health panel, and you will find that all 8 parts of your body have empty health, unable to send text in the chat bar, unable to load other blocks of the archive, and the kill command is invalid, causing damage to the archive. Unless a third party (such as the server backend or other operators) helps you display "You're dead!" To restore the interface, execute the kill command again on you.
## ScreenShots
![KABQX52}X}15TL8%2YM})T6](https://github.com/ichttt/FirstAid/assets/119282947/1356d0b7-c5ef-4323-8cf5-b0fa8c274cec)
![BO 7QXPK~4W~~)C9 R3NO3F](https://github.com/ichttt/FirstAid/assets/119282947/3e0b43fa-89ac-4545-a9e4-9970096e49c6)
![图片](https://github.com/ichttt/FirstAid/assets/119282947/0621c217-9bfa-4cab-9823-2122c3963f8e)

**Comment by ichttt** [comment]
I've only seen this bug happen on thrid-party mod loaders (e.g. CatServer or how it is called), and it does not happen on vanilla forge AFAIK. I think this is the case for you are well.

**Comment by MRFELIXSENIOR** [comment]
Well i got it in vanilla forge is there a fix to this?
