### ISSUE TITLE
issue when closing the game 1.20.1

### ISSUE THREAD

**Issue by CobaltGlacier** [ichttt/FirstAid#227]
it runs fine when i join the world, but upon leaving, the game crashes. this is the crash log i have.
[crash-2024-02-25_16.53.02-server.txt](https://github.com/ichttt/FirstAid/files/14398163/crash-2024-02-25_16.53.02-server.txt)

**Comment by miragliotta** [comment]
piggybacking off of this to say it's still present as of version 1.0 for forge 1.20.1 
[crash-2024-04-16_08.04.00-server.txt](https://github.com/ichttt/FirstAid/files/14998022/crash-2024-04-16_08.04.00-server.txt)

**Comment by ichttt** [comment]
Should be fixed in 1.20.1-1.1
