### ISSUE TITLE
Possible way to add / config new items into the mod?

### ISSUE THREAD

**Issue by CanecaKun** [ichttt/FirstAid#235]
I wanted to know if its possible to add more items, since we only have two healing items, and i wanted to add a medkit and maybe other items that would completely heal the body part in which its applied, and also config the time it takes to apply it.
I can easily config heal items with datapacks but i can only give instant health / regen effects and thats not what i want, i want to be able to have that cooldown to apply the item, and also config what it heals, is it possible?

Thanks!

**Comment by ichttt** [comment]
Other mods can integrate into FirstAid and add new healing items. This is currently not possible for datapacks, though
