### ISSUE TITLE
1.20.1 Crash when joining server

### ISSUE THREAD

**Issue by MoonSwallower** [ichttt/FirstAid#236]
When i try to join my friends server I crash upon joining with the error: The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "ichttt.mods.firstaid.common.registries.FirstAidRegistryLookups.DEBUFF_BUILDERS" is null

[launcher_log8.txt](https://github.com/ichttt/FirstAid/files/15195410/launcher_log8.txt)

**Comment by ichttt** [comment]
Sorry, but I cannot reproduce this. Does this always happen? Are other mods involved?

**Comment by ichttt** [comment]
Should be fixed in 1.20.1-1.1
