### ISSUE TITLE
[1.18.2] Game crashes upon exiting a world

### ISSUE THREAD

**Issue by CreepyForest2** [ichttt/FirstAid#237]
This was not a problem before, but it seems to be now. I have not tinkered with anything, and I have not updated/downgraded the mod. VERSION 1.11.1

crash report: 
[crash-2024-05-05_21.48.40-server.txt](https://github.com/ichttt/FirstAid/files/15214174/crash-2024-05-05_21.48.40-server.txt)

**Comment by ichttt** [comment]
Fixed in FirstAid 1.11.2
