### ISSUE TITLE
The blood volume is not evenly distributed. Please provide the relevant configuration file

### ISSUE THREAD

**Issue by Gao3721-1** [ichttt/FirstAid#238]
minecraft：1.20.1
![Snipaste_2024-05-13_22-03-47](https://github.com/ichttt/FirstAid/assets/169404712/67907993-df9d-4505-872a-8250a45dbdb2)

**Comment by netrantham** [comment]
There is a configuration file that can change those values called firstaid-server.toml. The file is located either in saves/YourWorldName/serverconfig or defaultconfigs.

**Comment by ichttt** [comment]
Yeah, there is a configuration file, as @netrantham pointed out.
