### ISSUE TITLE
Ticking player [1.20.1]

### ISSUE THREAD

**Issue by snlumi** [ichttt/FirstAid#241]
Player literal{player} is missing a damage model!
The contents of the error are as follows:
[crash-2024-06-15_20.04.34-server.txt](https://github.com/user-attachments/files/15846664/crash-2024-06-15_20.04.34-server.txt)
Armor containing mechanisms similar to the Totem of Undying in the Aquamirae mod will cause this error.
Also, the absorption effect of Totem of Undying is not applied properly (this causes the state to be equal to hp 1).
This error makes it impossible to connect to the server.

ticking entity in server
[crash-2024-06-18_02.29.06-client.txt](https://github.com/user-attachments/files/15875389/crash-2024-06-18_02.29.06-client.txt)

Unexpected error ( missing a damage model ) Error that occurred while setting up the server to fix the error
[crash-2024-06-18_02.55.24-client.txt](https://github.com/user-attachments/files/15875392/crash-2024-06-18_02.55.24-client.txt)

**Comment by snlumi** [comment]
Added: Totem of Undying also has a chance of causing the above error :<

**Comment by ichttt** [comment]
Should be fixed in 1.20.1-1.1
