### ISSUE TITLE
1.18.2 Ticking Exception for Modpack

### ISSUE THREAD

**Issue by RemadeFuture** [ichttt/FirstAid#242]
Hello! I'm working on a modpack for curseforge and my server and I want to use First Aid v1.11.0 jar from 1.18.2, I keep getting a ticking exception from missing damage model, is there any mods I can get rid of in order to keep the first mod in the modpack? 

![image_2024-06-26_193150778](https://github.com/ichttt/FirstAid/assets/46529923/0283b5f0-03e5-4023-8874-56df93d39433)
[crash-2024-06-26_19.06.15-server.txt](https://github.com/user-attachments/files/15997657/crash-2024-06-26_19.06.15-server.txt)

**Comment by ichttt** [comment]
Fixed in FirstAid 1.11.2
