### ISSUE TITLE
[1.12] Overlay disappearing

### ISSUE THREAD

**Issue by MasterEnderman** [ichttt/FirstAid#3]
If I change the position of the overlay, it just disappears. It only works, if i let it stay in the top-left corner.

Forge: 14.23.0.2512
First Aid: 1.2.4
Copy of the config: https://pastebin.com/9yy7z0HV

Keep up the good work!

**Comment by ichttt** [comment]
Thanks for your report! I am working on a fix right now

**Comment by ichttt** [comment]
Fixed in FirstAid 1.3.0, it will be online soon(tm)

**Comment by VirtualGaming1** [comment]
that was fast

**Comment by VirtualGaming1** [comment]
can i keep typing in here for other issue with other mods?
