### ISSUE TITLE
Bandages get used up on a single application

### ISSUE THREAD

**Issue by andrewminer** [ichttt/FirstAid#30]
### STEPS

1. Create a bandage the normal way
2. Get injured somehow
3. Right-click with the bandage in hand
4. Press and hold to apply the bandage to the injured part

### EXPECTED

The GUI closes with the bandage showing that it has three uses left.

### ACTUAL

The GUI closes and the bandage is removed from your inventory.

### DETAILS

Minecraft 1.12.2
First Aid 1.5.3

**Comment by ichttt** [comment]
Oh I see. The tooltip is written badly. It means it heals 4 times for half a heart. Will improve this in the next version.
This is not a bug, just a misleading tooltip. Thanks for the report!
