### ISSUE TITLE
SERVER SIDE ISSUE FOR FORGE

### ISSUE THREAD

**Issue by VirtualGaming1** [ichttt/FirstAid#34]
Right now on the forge version that you are using that i can not use due to server side of Forge getting startup error and unable to get that version to work on server. might want to wait right now using the version that is above remanded until Forge fix there server issue coding.

**Comment by ichttt** [comment]
Please provide the Log/Crash Report

**Comment by VirtualGaming1** [comment]
there is no log server did not even started and it is mainly forge issue. this is just a heads up for you that i can not run the latest version of your mode due to forge.

**Comment by VirtualGaming1** [comment]
you sure you tested on the "SERVER" but cause it is forge server side

**Comment by ichttt** [comment]
I tested dedi server
