### ISSUE TITLE
Damage with pvp disabled on server.

### ISSUE THREAD

**Issue by Zeyth-0x02f** [ichttt/FirstAid#35]
Good afternoon. Good afternoon.

I'm making a Minecraft server and wanted to use your mod, but I have a big problem, when with a plugin I disable PvP in certain areas like Spawn, players can still damage each other.

Would it be possible to solve this?

Thank you in advance.

**Comment by ichttt** [comment]
Can you tell me the name of the plugin and the SpongeForge version you use so I can try to reproduce it?

**Comment by Zeyth-0x02f** [comment]
Forge: 1.12.2 - 14.23.4.2705

Sponge: 1.12.2-2705-7.1.0-BETA-3361

Thanks you 👍

**Comment by ichttt** [comment]
Sorry no time to look into this...
