### ISSUE TITLE
First start with First Aid and scaleMaxHealth=true with maxHealth

### ISSUE THREAD

**Issue by roboderpy** [ichttt/FirstAid#36]
...already changed (scaling health for example) will cause all body's parts be not properly updated

![health](https://i.dbot.serealia.ca/2018/09/javaw_2018-09-11_11-01-23.png)

![menu](https://i.dbot.serealia.ca/2018/09/javaw_2018-09-11_11-01-44.png)

**Comment by roboderpy** [comment]
Seems to be another issue - In multiplayer, your health will be always at maximal, but actually it will be much lower.

**Comment by ichttt** [comment]
I fixed the desync with dedicated server with 594726e, but the current health = max health on start is a little bit more tricky, and I don't have time for that atm. I'll leave it open though

**Comment by roboderpy** [comment]
Is there something can be done about this? ![pic](https://i.dbot.serealia.ca/2018/09/javaw_2018-09-12_11-15-32.png)

**Comment by ichttt** [comment]
Yeah, right. FP precision. Shouldn't be too hard to fix

**Comment by ichttt** [comment]
Everything that was left should be fixed by 8c5ee7715ae7d1ff794f885bca218f8788cad24e

**Comment by roboderpy** [comment]
thanks
