### ISSUE TITLE
Mods which modify health directly (?) with otherRegenMultiplier will bug out body's parts

### ISSUE THREAD

**Issue by roboderpy** [ichttt/FirstAid#38]
capMaxHealth must be false and scaleMaxHealth must be true
How to reproduce:
1. Install Scaling Health
2. Install First Aid
3. Make sure otherRegenMultiplier is lower than 1.0 and in Scaling Health config hearts not only increase max health but also heal (both are enabled by default), and set `S:"Health Text Style"=HEALTH_AND_MAX` in Scaling Health config (for visuals)
4. Give yourself heart containers and increase your health
5. Your "real" (the technical one) health will increase but healing will be a bit weird. When you heal to the max you will find out that some of your body parts are not fully healthy altrough your health is already on max

This issue **can not** be reproduced if otherRegenMultiplier = 1.0 and because of https://github.com/ichttt/FirstAid/issues/36 it is only reproducable in sinlgleplayer

*Played with this mod for 20 minutes for proving grounds and i already in love with it, but there are some lil bugs i found, which are not game breaking but rather a bit annoying*

**Comment by ichttt** [comment]
I can't reproduce this with my latest changes. Please try to reproduce and reopen if the issue persists in the latest version (should be on CurseForge in a bit)

**Comment by roboderpy** [comment]
Seems to be fixed. Yay!
