### ISSUE TITLE
FTBUtl Commands not working and mod cap.

### ISSUE THREAD

**Issue by VirtualGaming1** [ichttt/FirstAid#4]
Neat mod not showing the actual average health and the FTBUtl command "Heal" is not healing players

**Comment by VirtualGaming1** [comment]
might want to addon to PlayerRevive also: https://minecraft.curseforge.com/projects/playerrevive?gameCategorySlug=mc-mods&projectID=266890

**Comment by ichttt** [comment]
Can you please specify what you mean with your first part of your first message?

**Comment by ichttt** [comment]
The FTBU thing is because FTBU calls setHealth instead of heal, which I don't intercept atm. Will change in the next few days.

**Comment by VirtualGaming1** [comment]
ok and I like this mod too will keep you up to date if i find more issue
