### ISSUE TITLE
Startup crash with latest Forge release for 1.12.2

### ISSUE THREAD

**Issue by ChinChopper** [ichttt/FirstAid#42]
Recently the forge version 14.23.5.2768 has become recommended and this mod is causing crash in the game after initialization.
Says LexMano in this session (3th comment)
http://www.minecraftforge.net/forum/topic/66711-forge-1122-142342768-startup-crash/

**Comment by ichttt** [comment]
FirstAid does not touch RenderChunk, the coremod only transforms Potion. Most likely optifines fault, otherwise you have to start removing mods and see what really causes this

**Comment by ChinChopper** [comment]
Ok, thanks =)
And sorry, I do not know to see a log, Lexmanos gave me a list with the mods that said in the LOG in "warning", so I decided to report.
