### ISSUE TITLE
Healing not working during sleep

### ISSUE THREAD

**Issue by andrewminer** [ichttt/FirstAid#43]
### PROBLEM

I've configured the settings to allow the player to recover 50% health during sleep, but when I actually sleep, no health is restored.

### EXPECTED

With my current settings, I'd expect that when I go to sleep in this condition, I would wake up completely healed.

![image](https://user-images.githubusercontent.com/445000/50554815-489adf80-0c7f-11e9-963b-a4e8739d2ac8.png)

### VERSIONS

Minecraft: 1.12.2
Forge: 14.23.5.2776
First Aid: 1.6.2

Full Mod List: [Brunel2 Mods](https://github.com/andrewminer/brunel2/tree/master/mods)
Configurations: [Brunel2 Configs](https://github.com/andrewminer/brunel2/tree/master/config)

Of note: This is a multiplayer server which uses Morpheus.  We have noticed that only the person(s) who are actually in bed are healed.  However, in this case, only one player was actually logged on to the server.

**Comment by ichttt** [comment]
Thanks for the nice report! Should be fixed in 1.6.3, which will be released once CF approves
