### ISSUE TITLE
Blood Magic compatibility

### ISSUE THREAD

**Issue by DevTimur** [ichttt/FirstAid#45]
With your mod when you use Sacrificial dagger, you get healed instantly.

**Comment by ichttt** [comment]
What is the expected behavior? I don't know Blood Magic well...

**Comment by DevTimur** [comment]
You expected to lose 0.5 heart per rightclick.
There is also charged rightclick, you lose all health exept of 0.5 heart.
And there is also a ritual draining you health 0.5 heart per second.

**Comment by DevTimur** [comment]
https://i.gyazo.com/5f7050756f03fa85fe1960eb8b51fdec.gif
Instead of hurting it healing.

**Comment by ichttt** [comment]
Try enabling experimentalSetHealth (Can be found under Main Menu -> Mods Button -> Click on First Aid in the list -> Config Button -> Show more -> experimentalSetHealth ). It might fix this issue.

**Comment by DevTimur** [comment]
Already on. I use scaling health mod

**Comment by ichttt** [comment]
Should be fixed by 8c5ee7715ae7d1ff794f885bca218f8788cad24e
