### ISSUE TITLE
Death Conflict with Regeneration Mod (Suffril)

### ISSUE THREAD

**Issue by ghost** [ichttt/FirstAid#48]
Problem occurs when head/body is critically damaged.

Expected behavior: Player's hand glows, eventually player regenerates with new skin, and all health bars are restored.

Actual behavior: Player will die, but the glowing hand will start anyways. They can close the death screen with ESC, and the death animation will play, but broken. (twitching, and not disappearing), however they can regenerate and play normally besides the broken death animation.

[https://github.com/Suffril/Regeneration/issues/186](Their github)

**Comment by ichttt** [comment]
Issue is very old, if it still isn't resolved by another bugfix, feel free to reopen
