### ISSUE TITLE
Enhanced Visual Capability ideal

### ISSUE THREAD

**Issue by VirtualGaming1** [ichttt/FirstAid#5]
Hi I just would like to make this to get some ideals on what visual effect that would be nice to see if a certain part is low on health
#https://github.com/CreativeMD/EnhancedVisuals/issues/23
#https://github.com/VirtualGaming1/Real-Life-Modpack/issues/1

Comment in one of these or this for your ideas.

**Comment by VirtualGaming1** [comment]
@ichttt thanks for making an API for other modders this will help them to get there mod work better with this. and liking the mod too.

**Comment by ichttt** [comment]
Sorry but this isn't going to happen in the near future.
