### ISSUE TITLE
[1.14.4] Skeletons + First Aid = One-shot kill

### ISSUE THREAD

**Issue by Gamertech** [ichttt/FirstAid#51]
Skeletons got a bit of a buff with 1.14 and when shot by them with First Aid it's pretty much a guaranteed 1-hit kill even wearing full mid-tier armour.

All other mobs seem fine enough, causing injury/debuffs but survivable even with zero armour. Skeletons are currently in orbital strike mode however especially in hardcore mode.

Is it possible to get some tweaking to balance out incoming arrow damage if possible?

Cheers

**Comment by ichttt** [comment]
Fixed in latest first aid. On normal difficulty, skeletons are no longer able to headshot you, even if you just wear a leather helmet. Your Leggings do not protect you as good as before anymore in exchange though (but this is minor)

**Comment by Gamertech** [comment]
Excellent. I'll test as soon as I get a chance. Cheers for the fix.
