### ISSUE TITLE
Tinkers compatibility issue

### ISSUE THREAD

**Issue by Scortan** [ichttt/FirstAid#53]
Like the mod
does not work with tinkers armour
example
diamond helmet gives like 13? location defence
tinkers helmet give lets say 15 defence so it should be stronger but no
the tinkers helmet does not become specific to location and since there hp bar it gives not defence at all meaning that all tinkers armour has 0 defence if using this mod.
plz look into it i Iike this mod but its pretty annoying if using tinkers and a modpack where there is a lack of diamonds and vanilla materials. i get 1 shot by most mobs that are slightly stronger than vanilla stuff. even skeles with slightly stronger bows always get head shot insta kills.

lots of love
some dude

**Comment by ichttt** [comment]
I can't find a mod called tinkers armor, and I don't think tinker's construct has armor. Can you send me a link to the mod?

**Comment by gmmachado15** [comment]
https://www.curseforge.com/minecraft/mc-mods/constructs-armory

**Comment by AfroZenPizza** [comment]
I noticed the same behavior, but I believe it has to do with the way that Construct Armory calculates defense based on user choice vs having a fixed defense.
If you take the base items (for example comarm:helmet) it has 0 for defense durability and toughness. The defense, traits, and attributes are based on NBT tags.
I may just be stupid, but an if conitdional for conarm that then reads the NBT tag called Stats for defense or toughness could fix it. 
If you decide to implement compatibility I would be greatful, but I can understand not implementing it while focusing on the 1.14.x releases. 
Even if you decide not to, just giving me a hint as to where to look to implement this in the code, and I would fork it.

Thanks for all the awesome work. Keep it up!

**Images of base helmet item and higher tier helmet item for ingame comparison:**

![image](https://user-images.githubusercontent.com/6499672/67137213-29157900-f1f7-11e9-8022-8f459fd5793f.png)
 
![image](https://user-images.githubusercontent.com/6499672/67137231-7691e600-f1f7-11e9-9ac4-8d60a679f1bc.png)

**NBT Data for Up-Tier Helmet**
![image](https://user-images.githubusercontent.com/6499672/67137357-4f3c1880-f1f9-11e9-838f-0d83d40868b4.png)

**Comment by ichttt** [comment]
Fixed in 1.6.11
