### ISSUE TITLE
No Head hp, but not dead

### ISSUE THREAD

**Issue by black0039** [ichttt/FirstAid#55]
Using healing items or sleeping in a bed doesnt fix the problem, Using RLCraft
![2019-10-08_21 41 25](https://user-images.githubusercontent.com/56328997/66445618-60c13b80-ea15-11e9-9ed3-ed5d2ef878e4.png)

**Comment by ichttt** [comment]
Can you send me the save where this is happening?

**Comment by ichttt** [comment]
Fixed in 2f019911a94c886c014101f0ef8f1754c9a4bf83
