### ISSUE TITLE
Poison damage causing non-registered death

### ISSUE THREAD

**Issue by AstrumLeonis** [ichttt/FirstAid#58]
Using the First Aid 1.6.10 for Minecraft 1.12.2

With Head and Body instance death disabled in the config if the Poison condition reduces you to half a heart as it normally does, for some reason with First Aid installed Poison's continuous damage ticks have the potential to cause death. Unfortunately if you die via this method Minecraft doesn't recognize your death and you do not trigger any on death effects via vanilla or from mods and it deletes all of your items and experience.

**Comment by ichttt** [comment]
Fixed in 1.6.11
