### ISSUE TITLE
Small issue with average health

### ISSUE THREAD

**Issue by VirtualGaming1** [ichttt/FirstAid#6]
The average health dose not display right and instead it showing the MC health. Do not know that is caused by CreativeMD Enhanced Visual

**Comment by ichttt** [comment]
Can you please post screenshots of the problem and specify what you mean with "MC Health"

**Comment by VirtualGaming1** [comment]
will do but I have notice that you have an update so let me test it with the update first.

**Comment by VirtualGaming1** [comment]
![2017-11-11_14 38 42](https://user-images.githubusercontent.com/20447403/32693434-95fe780c-c6f0-11e7-847c-9cdac74d5481.png)
It also causing another bug.
the Game thinks you are dead so you are not able to intract with blocks that have a GUI unless i do /Heal and /Heal dose not heal the body parts still

**Comment by ichttt** [comment]
Heh, I found a bug that may cause the current health to be set to infinite or negative infinite... That may be the solution to the last problem, but I'm not sure if it fixes the first one as well, testing right now. I can upload you a debug build if you want to test it, too before I upload it to CurseForge

**Comment by ichttt** [comment]
Here is a debug build. Just unpack it and put it into your the jar into your mods folder (don't forget to delete the old file) and it should work.
[firstaid-1.3.3-DBG.zip](https://github.com/ichttt/FirstAid/files/1464160/firstaid-1.3.3-DBG.zip)
I will publish the new version tomorrow if no new bugs are found and this one is confirmed fixed.

**Comment by VirtualGaming1** [comment]
ok will test it im going to test it

**Comment by VirtualGaming1** [comment]
I do have a discord server and if you want to join (or anyone else) here is a link
@ichttt let me know when you get in if you do choose so, so i can add a role to you

**Comment by VirtualGaming1** [comment]
@ichttt it works right now and are there a way that the average health set MC health with a set time or with an event like when you get hit or a body heart recovers? but other then that the bug about the GUI bug will be fix as MC will not think that the player is dead.

**Comment by VirtualGaming1** [comment]
hold the update for a sec i think i found a game braking bug im doing more testing right now that i think that the body parts health is not recovering

**Comment by VirtualGaming1** [comment]
just did a further testing is that when i kill my self first time that i used /kill and at the time i have a mod called PlayerRevive so after i revive my self and used the bandages and wont heal the body parts. so i just hurt my self by fall damaged and use the bandages and it works. so i just found a small bug that is not game braking unless a admin us /kill command on a player

**Comment by ichttt** [comment]
Dammit I thought I fixed compat with this release, just this thing was not tested^^. Found the issue, should be good to go now.
