### ISSUE TITLE
Broken GUI

### ISSUE THREAD

**Issue by GeckGlobal** [ichttt/FirstAid#62]
Player_Model is swinging like it is on a hinge. I am using a fresh installation of 1.12.2-forge1.12.2-14.23.5.2847 and no other mods.
![Player_Model](https://user-images.githubusercontent.com/22286207/67894864-8d4c1b80-fbad-11e9-8432-004496ecbade.gif)

**Comment by Charles445** [comment]
It's haunted!

It'll go away tomorrow (or you can disable it in your config, "enableEasterEggs")

**Comment by GeckGlobal** [comment]
Well its not broken so thats a good thing. I seriously thought it was a bug.
