### ISSUE TITLE
Shields do not negate damage on Sponge Forge servers

### ISSUE THREAD

**Issue by T0ED** [ichttt/FirstAid#66]
I am currently running

    SpongeForge version: 7.1.7
    Forge version: 14.23.5.2838
    Java version: Java 8 Update 191 (64 bit)
    Operating System: Windows 10
   Minecraft Version 1.12.2

Mods:
Sponge 1.12.2-7.1.7
firstaid 1.6.12 

Plugins:
No additional plugins

Issues:
Shields do not negate any damage. This issue is only present when running on a Sponge Forge server.

Logs:
_There is no applicable log as this misbehavior does not produce any logs._

**Comment by ichttt** [comment]
Sounds like an issue with SpongeForge, please report to them

**Comment by T0ED** [comment]
Alright, will do.
