### ISSUE TITLE
[Feature Request] Config for Death via Status Effect

### ISSUE THREAD

**Issue by znaxcy** [ichttt/FirstAid#68]
Currently, it seems hunger will kill me. A config option to leave a half a heart, even when hunger just affects the body (hardMode=true), would be lovely.

Regarding other status effects, Tough as Nails has hypothermia and hyperthermia status effects that aren't supposed to kill the player by default, but with First Aid they seem to randomly assign damage to body parts, thus killing the player by removing all points from the head or body, I'm guessing leaving that "last hp" somewhere else on the body instead. Though I haven't experimented too much, I'm guessing this is the same with a lot of damaging status effects.

Would it be possible to create a config option to leave half a heart on each head and body when it comes to injury mechanisms like these that cause seemingly randomly assigned damage?

Obviously it'd be great to see hypothermia affect distal limbs, then proximal limbs (as a human body would move blood to the core in a RL hypothermia situation) but since I'm sure there are dozens of status effects out there that cause damage and configuring each of them to behave a certain way is a lot to ask, it'd be nice to at least be able to configure if the player will die or not as you usually can with the old, inferior healthy system.

Thanks! Keep up the great work!

**Comment by ichttt** [comment]
The Tough as Nails authors can use the FirstAid API to add support for locational damage. Option to switch the default random distribution to a distribution, that tries to keep the player alive if there are enough non-critical limbs will be added in the next release.

**Comment by ichttt** [comment]
Config option implemented in 1.6.13
