### ISSUE TITLE
Compat with sleep-timelapse mods?

### ISSUE THREAD

**Issue by ScarlettShooter** [ichttt/FirstAid#69]
It would be great if this mod has compat with mods that makes night unskippable, in example SleepingOverhaul. I'm not really good coder but it's not too hard to do, just check if there is some sleep overhauling mod or just do it through "true; false" in config and check if entity[Player] is on the bed and give him some kind of Regen. It's how it might work IMO(you sleeping and restoring health, not just skip night to heal 7% of health). Anyway thx for such great mod)

**Comment by ichttt** [comment]
This mod has morpheus integration right now, so just use morpheus, or is this mod different from morpheus?

**Comment by ScarlettShooter** [comment]
It's different. Morpheus just sleep-voting system. Sleeping Overhaul makes sleeping on bed increase tickrate, so 1 real tick is 1000 ticks on bed(configurable). So to sleep night you need to wait

**Comment by ichttt** [comment]
Sorry, it looks like this mod has no public API that exposes any of the information needed for FirstAid to do this. It's on their side to either add an API that exposes which players slept or add compat for FirstAid themselves
