### ISSUE TITLE
[Incompatibility] Spice of Life: Carrot Edition and First Aid, Eating food kills you

### ISSUE THREAD

**Issue by dreckz** [ichttt/FirstAid#76]
**MC: 1.15.2
First Aid Version: 1.8.0
SoL:CE Version: 1.9.4**

When attempting to eat food with Spice of Life enabled, it ends up reducing your hp for some reason.  Tried using this with hunger strike in conjunction with these two mods, and it severely reduces HP.

**Comment by juliand665** [comment]
I'm curious in your opinion on this, @ichttt, but I wonder if it's even realistic to have our mods be compatible with each other—we increase the max health as the player tries new foods, but it doesn't seem like that would translate to First Aid very well.

**Comment by ichttt** [comment]
FirstAid has a config option called `scaleMaxHealth` that adjusts first aid hearts if the vanilla max health changes. If it's just max health that isn't working, that might be a possible solution for this

**Comment by ichttt** [comment]
As said in https://github.com/ichttt/FirstAid/issues/115, the incompatiblity is resolved now.
