### ISSUE TITLE
Overlay doesn't show up on the right side

### ISSUE THREAD

**Issue by Owbb** [ichttt/FirstAid#77]
When switching the overlay to TOP_RIGHT or BOTTOM_RIGHT and having the health show as HEARTS or NUMBERS nothing shows up. Mod version 1.6.10 I'm playing on v2.7 of RLcraft for clarification.

**Comment by ichttt** [comment]
For future bug reports, please always use latest first aid. Fixed by  for 1.12, will be released to CF this week. Other minecraft versions will be fixed soon(tm) as well
