### ISSUE TITLE
1.14 healing via sleep doesn't work

### ISSUE THREAD

**Issue by LuckyChickens** [ichttt/FirstAid#78]
I am not healing at all whenever I sleep. I have confirmed this by going in a creative world, entering survival, injuring myself, then repeatedly setting the time to night and sleeping with no healing occurring whatsoever. Bandages work fine.

I have firstaid-1.7.11

Here are all the mods I have installed:
angel ring
appleskin
attribute fix
autoreglib
better animals plus
better foliage
biomes o plenty
bountiful baubles
carry on
chance cubes
comforts
compact ores
corpse
crying ghasts
curios api
dynamic surroundings
fast leaf decay
first aid
forgiving void
friendly fire
just enough items
just enough resources
klee slabs
let sleeping dogs lie
lost cities
lycanites mobs
move plus
mr. crayfish's furniture mod
music player
mystical wildlife
neat, paintings ++
pretty beaches
quark
ruins
save my stronghold
serene seasons
softer hay bales
storage drawers
swing through grass
tool belt
u team core
unique enchantments
villager names
waila
waystones
wesserboy's overlays
xp tome
yung's better caves

**Comment by ichttt** [comment]
Just tested with only first aid, that seems to work. Most likely a mod conflict, reduce your modlist until you find which mod causes this

**Comment by rckymtnrfc** [comment]
I just ran into this issue with the 1.15.2 version.  Did some testing and found that Quark has a setting called Improved Sleeping.  You need to set that to false but also under the settings for Improved Sleeping, turn off AFK also.

[tweaks.improved_sleeping]
		"Enable Afk" = false
		"Afk Time" = 2400
		"Percent Req" = 1.0

That fixed the issue for me.

**Comment by ichttt** [comment]
Ah ok that helps a lot, I'll see what I can do, there is probably some new event I missed

**Comment by LuckyChickens** [comment]
I'll turn that off and see if it works. Thank you.

**Comment by ichttt** [comment]
Fixed for 1.15.2 and 1.16.1. Use version 1.8.2 or above
