### ISSUE TITLE
1.12.2 Natural Regen still works

### ISSUE THREAD

**Issue by ReverseNutsack** [ichttt/FirstAid#79]
Natural Regen still works even though naturalregen is labeled as false ingame and the cfg file (1.6.12)

**Comment by ichttt** [comment]
Make sure no other mod like scaling health has natural regen enabled. If you still don't know where the healing is comming from, enable debug in the first aid config and send a debug log please.

**Comment by ichttt** [comment]
Make sure no other mod like scaling health has natural regen enabled. If you still don't know where the healing is comming from, enable debug in the first aid config and send a debug log please.

**Comment by ichttt** [comment]
Oh, and also make sure you test on the latest version (1.6.13)

**Comment by ReverseNutsack** [comment]
indeed scaling health was the problem, thanks :>
