### ISSUE TITLE
[Incompatibility] Combined with Scaling Health mod, health desyncs upon restart of game.

### ISSUE THREAD

**Issue by D-Bigboy-302** [ichttt/FirstAid#83]
When combined with Scaling Health from Silentchaos, upon restarting the game your limb health won't heal back up fully. It shows your limbs full health but won't heal all the way. The amount it heals appears to be random too.

I am using the latest 1.14 version along with optifine, if it matters.

**Comment by D-Bigboy-302** [comment]
Issue was on Scaling Health's side. Issue was fixed.

**Comment by alexphl** [comment]
I'm experiencing the same issue, what was your fix?
