### ISSUE TITLE
No food bar texture while there's a boss bar

### ISSUE THREAD

**Issue by Gremter** [ichttt/FirstAid#84]
**MC: 1.12.2**
**First Aid Version: 1.6.14**

When you enter any boss battle with the boss bar textures of food change to white.
When you exit the boss bar region the food bar just goes back to normal.

Tried to test with only First Aid without changing anything and the problem still occurs .

**Comment by roccscout** [comment]
I had the same issue with 1.6.14, and now with 1.6.15. I'm not sure how/why more people aren't posting about this issue. It makes boss fights unplayable, to be honest.

**Comment by ichttt** [comment]
Fixed in latest 1.12.2 and 1.16.5 versions
