### ISSUE TITLE
[1.12.2] Armor and Armor toughness qualities from Quality Tools don't work

### ISSUE THREAD

**Issue by 04Slash** [ichttt/FirstAid#85]
Forge: 14.23.5.2838
First Aid: [1.6.14](https://www.curseforge.com/minecraft/mc-mods/first-aid/files/2917456)
Potion Core (Dependency for QT): [1.9_for_1.12.2](https://www.curseforge.com/minecraft/mc-mods/potion-core/files/2905184)
Quality Tools: [1.0.7_for_1.12.2](https://www.curseforge.com/minecraft/mc-mods/quality-tools/files/2732994)
Baubles (Dependency for BB): [1.12-1.5.2](https://www.curseforge.com/minecraft/mc-mods/baubles/files/2518667)
Bountiful Baubles: [1.12.2-0.1.5](https://www.curseforge.com/minecraft/mc-mods/bountifulbaubles/files/2879450)

Due to the armor changes from First Aid having armor and armor toughness qualities from both [Qualities tools (Stats shown)](https://imgur.com/a/aIVNOAF) and [Bountiful baubles (Stats shown)](https://imgur.com/a/fnSKQMJ) does not work.
These tests were done in v2.8.2 of RLCraft. Natural Regeneration is disabled. [Spreadsheet](https://docs.google.com/spreadsheets/d/1U-Lex0Z_g9AioAcTGHaVGwIRHdXQ8MqhivlAfn2AZvA/edit#gid=0) of my test results that show that these stats do not do anything.
I have also conducted some tests (also shown in the spreadsheet) that these qualities do in fact do something when removing just the first aid mod.
If you need any more information let me know. I will also do more testing if you feel my tests were not conclusive enough. Just let me know what you want me to test.

**Comment by ichttt** [comment]
Please retest with 1.6.15. It should be fixed

**Comment by 04Slash** [comment]
I got around to testing this. It seems that everything is working as intended now.

Armor and Armor toughness on armors are reducing, or increasing, damage done. This also applies to any armor and armor toughness stats on baubles.

Thanks for your hard work and contributions to the modded minecraft community! <3
