### ISSUE TITLE
No heart GUI  in survival [1.12.2]

### ISSUE THREAD

**Issue by KPV444444444** [ichttt/FirstAid#87]
Well i use some mods that i think are compatible with First Aid, But everytime i go to survivial, the game glitches out and doesnt give me the heart gui. Please tell me what to do or something
![image](https://user-images.githubusercontent.com/64782999/80962038-888e4b80-8e0c-11ea-8a05-447d410153d4.png)

**Comment by VirtualGaming1** [comment]
have you change the config of First Aid that it show up?

**Comment by ichttt** [comment]
This is intentional, first aid disables the hearts HUD, as they no longer respresent the actual life, and first aid has another hud to display per-limb health. You can however reenable the hearts in the First aid config under the "Overlay" Section
