### ISSUE TITLE
Can't change naturalRegeneration to true in the config at all!

### ISSUE THREAD

**Issue by yourizuring** [ichttt/FirstAid#88]
I am using the latest version for 1.15.2, and there is no way to change naturalRegeneration **anywhere** in the config, tho the mod page in curseforge said there is. If there is, WHERE in the config can I change this?!

**Comment by ichttt** [comment]
it is in the server config, meaning the it can be changed per-world, so in your world folder (e.g. saves/my super world), there will be a config folder with a first aid config. If you want this to apply for all new worlds as well, copy the first aid server config into the defaultconfigs folder in the .minecraft folder. Note that you have to change this for all your worlds if you want this change.
