### ISSUE TITLE
Cant respawn

### ISSUE THREAD

**Issue by Ahhyourbad** [ichttt/FirstAid#90]
Hello, Im running a 12,2 cat server with just one mod on it. Now when I die it wont let me hit the respawn button,. It will only let me go to title screen and than I can rejoin the server, but it like rolls back on me before I died. I've removed the mod and restarted my server and it works fine I can respawn and everything.
Its going to be a core mod in my pack and I really need to fix this some how. Any Ideas would be awesome!

**Comment by ichttt** [comment]
Talk to cat server people, it works fine with normal forge, which is the main target. I guess they somehow mess with the EntityDataManager

**Comment by Ahhyourbad** [comment]
I talked to them. which they replied to as we don't do fixes for one mod. Anyway I could get a fix for this? Even willing to pay for a fix, because this is a core mod and it needs to be on the server there is not another like it.

**Comment by you-hengh** [comment]
me too  I also encountered this problem, help!!

**Comment by Catlord-3** [comment]
Im pretty sure this happens when you have a lot of mods loaded at the same time, happened to me once with a modpack
just ask them if they can remove some unnecessary mods that eat up a lot of data (ex: mods that add in a bunch of redundant things, like 500 blocks, or mods that do very complex operations that are not integral to gameplay, or you just don't care about.), or maybe turn down graphics settings (1 i know will work, 2 requires testing)

**Comment by Ahhyourbad** [comment]
As I said before I only have 1 mod on the server. Its first aid. I've tried this mod on cat server, magma and it does not let me respawn. It works on sponge forge but I really done want to use it because of the support is not that great. Plus regular forge you cant do any plugins. The issue is when your player reaches 0 health you die =, but when you try to hit respawn you cant. You can spam it, but it wont do anything. Now if you hit title menu and than go back and join the server it reverts you back before you died, but makes it where your a one hit.

**Comment by ichttt** [comment]
So yeah, this is definitly an issue with custom minecraft servers that modify how health is stored and synced. I can't do much there. It is really on the creator of the server software to fix this issue, or at least give me a hint what I need to change to achive compat.

**Comment by Ahhyourbad** [comment]
should I make a video of the issue?

**Comment by ichttt** [comment]
Closing, as it's an issue with custom unsupported server software. Not much I can/am willing to do
