### ISSUE TITLE
Armor Attributes not working properly/not working at all.

### ISSUE THREAD

**Issue by Catlord-3** [ichttt/FirstAid#99]
Basically what is happening is your mod does not look at attributes of armor (armor can be given attributes with commands) at all. I tested this out with a helmet that should pretty much make me invincible to head damage (+1000 armor and +1000 armor toughness) and it seemed to only help as much as a regular leather helmet without the attributes. Tested with skeleton, compared with forgotten items golem helmet on how many hits to take 3 hearts of head health away (golem armor 7-8, OP leather helmet 2) I really hope you can fix this as i think this also causes a conflict with quality tools. I am using the latest 1.12 version, 1.6.14. Please fix this as i really like this mod, but this is a really annoying bug.

(extra notes: i made sure to use the same skeleton for this test and did not have anything on me that should effect the outcome, and no other mobs were around that could effect the outcome.)

[https://minecraft.gamepedia.com/Attribute](https://minecraft.gamepedia.com/Attribute) Wiki on attributes, contains commands for newer versions, but should explain them. I reccomend downloading a nbt editor mod to test as this makes it easier to get the modified gear, instead of typing out a command (i used a CLIENT SIDE only one, https://www.curseforge.com/minecraft/mc-mods/infinity-item-editor)

**Comment by ichttt** [comment]
Fixed in 1.6.15 beta for mc 1.12.2. If no bigger issues arise, this will be promoted to a release soon, and a version for 1.16 will follow.
